# Data Cleaning Project

## Objective
Clean and prepare dataset(s) for analysis/reporting.

## Scope
- Handle missing values
- Remove duplicates
- Fix data types
- Normalize text
- Validate data quality

## Output
- Clean dataset (CSV)

In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)
pd.set_option('display.width', None)

In [2]:
df=pd.read_csv("data.csv")
df.head()

  receipt_no     sale_date   customer_name   contact_no        branch     item_desc    qty unitPrice total_amt pay_status    amt_paid                   source_note
0     R10000    2025/06/13   SARA MOHAMED   01089254563      DOWNTOWN   Coffee 200g      2       110    220.00       paid  EGP 220.00  Dashboard | first-time buyer
1     R10001   25-Jan-2025     Salma Nabil  01084093639   Heliopolis   Orange Juice  2 pcs        38     76.00       paid       76.00     CRM export | new customer
2     R10002    2025/01/19     Nadia Tamer  01153524491     NASR CITY         Chips      5        22    110.00       Cash      110.00           POS | promo applied
3     R10003    30-05-2025   Mostafa Samir  01030514014    Heliopolis      Rice 1kg      2        48     96.00  COMPLETED       48.00   Manual Excel | new customer
4     R10004  Jun 10, 2025       Yara Atef  01275579548     Madinaty   Orange Juice      2       $38    76.00        Paid       76.00                     POS | vip

In [3]:
# === BEFORE CLEANING (Quick Snapshot) ===

print(f"Shape: {df.shape[0]} rows × {df.shape[1]} cols")

print("\nMissing :")
display(df.isna().sum()[lambda x: x!=0].sort_values(ascending=False))

print("\nDuplicates:", df.duplicated(subset=["receipt_no","item_desc"]).sum())

print("\nSample:")
display(df.head(3))

Shape: 338 rows × 12 cols

Missing :

contact_no       17
amt_paid         15
customer_name    10
total_amt         8
unitPrice         7
receipt_no        6
sale_date         6
dtype: int64

Duplicates: 9

Sample:

  receipt_no    sale_date   customer_name   contact_no        branch     item_desc    qty unitPrice total_amt pay_status    amt_paid                   source_note
0     R10000   2025/06/13   SARA MOHAMED   01089254563      DOWNTOWN   Coffee 200g      2       110    220.00       paid  EGP 220.00  Dashboard | first-time buyer
1     R10001  25-Jan-2025     Salma Nabil  01084093639   Heliopolis   Orange Juice  2 pcs        38     76.00       paid       76.00     CRM export | new customer
2     R10002   2025/01/19     Nadia Tamer  01153524491     NASR CITY         Chips      5        22    110.00       Cash      110.00           POS | promo applied

In [4]:
df.info()

df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   receipt_no     332 non-null    object
 1   sale_date      332 non-null    object
 2   customer_name  328 non-null    object
 3   contact_no     321 non-null    object
 4   branch         338 non-null    object
 5   item_desc      338 non-null    object
 6   qty            338 non-null    object
 7   unitPrice      331 non-null    object
 8   total_amt      330 non-null    object
 9   pay_status     338 non-null    object
 10  amt_paid       323 non-null    object
 11  source_note    338 non-null    object
dtypes: object(12)
memory usage: 31.8+ KB

       receipt_no    sale_date customer_name   contact_no     branch     item_desc  qty unitPrice total_amt pay_status amt_paid       source_note
count         332          332           328          321        338           338  338       331       330        338      323               338
unique        321          283            55          314         15            42   17        37       116          9      128               108
top        R10083  23-Jun-2025   Nadia Tamer  01211286267  Nasr City  Orange Juice    2        38     48.00    Partial    48.00  POS / manual fix
freq            2            3            19            2         68            28  100        28        14         54       17                12

In [5]:
for col in df.select_dtypes(include="object"):
    print(f"{col}")
    print(df[col].unique()[:10],"\n")

receipt_no
['R10000' 'R10001' 'R10002' 'R10003' 'R10004' 'R10005' 'R10006' 'R10007'
 'R10008' 'R10009']

sale_date
['2025/06/13' '25-Jan-2025' '2025/01/19' '30-05-2025' 'Jun 10, 2025'
 '2025-06-26' '02-May-2025' '2025-02-12' 'Jun 02, 2025' '2025/03/04']

customer_name
[' SARA MOHAMED ' 'Salma Nabil' 'Nadia Tamer' 'Mostafa Samir' 'Yara Atef'
 ' AYA FATHY ' 'Dina Kamal' 'Omar Said' 'Mr. Eslam Fouad / VIP'
 'Hassan Ibrahim']

contact_no
['01089254563' '01084093639' '01153524491' '01030514014' '01275579548'
 '01140158366' '01097705310' '01545594951' '01066267415' '01299038526']

branch
['DOWNTOWN' ' Heliopolis ' 'NASR CITY' 'Heliopolis' ' Madinaty '
 'HELIOPOLIS' 'Nasr City' 'Maadi' 'Madinaty' 'Downtown']

item_desc
['Coffee 200g' 'Orange Juice' 'Chips' 'Rice 1kg' ' Soap Bar ' 'Bread'
 'Yogurt Cup' 'Soap Bar' 'Eggs 12pc' ' Shampoo ']

qty
['2' '2 pcs' '5' '5 pcs' '1' '3' ' 3 ' '4' ' 4 ' '0']

unitPrice
['110' '38' '22' '48' '$38' '18' nan '16' '72' '110.00']

total_amt
['220.00' '76.00' '110.00' '96.00' ' 76.00 ' '90.00' '12.00' '32.00'
 ' 18.00 ' '216.00']

pay_status
['paid' 'Cash' 'COMPLETED' 'Paid' 'pending' 'Partial' 'PAID' 'Card'
 'completed']

amt_paid
['EGP 220.00' '76.00' '110.00' '48.00' '90.00' '12.00' '16' '18.00'
 '216.00' '330.00']

source_note
['Dashboard | first-time buyer' 'CRM export | new customer'
 'POS | promo applied' 'Manual Excel | new customer' 'POS | vip'
 'pos | checked by cashier' 'POS / manual fix' 'dashboard | legacy import'
 'pos | walk-in' 'CRM+Manual | quick sale']

In [6]:
df.describe()

       receipt_no    sale_date customer_name   contact_no     branch     item_desc  qty unitPrice total_amt pay_status amt_paid       source_note
count         332          332           328          321        338           338  338       331       330        338      323               338
unique        321          283            55          314         15            42   17        37       116          9      128               108
top        R10083  23-Jun-2025   Nadia Tamer  01211286267  Nasr City  Orange Juice    2        38     48.00    Partial    48.00  POS / manual fix
freq            2            3            19            2         68            28  100        28        14         54       17                12

## Detected Issues

- Missing values in: contact_no, amt_paid, customer_name, total_amt, unitPrice, receipt_no, sale_date
- Duplicates: there are 9 rows duplicated
- Inconsistent text: Columns show inconsistent formats and casing: mixed date formats in sale_date, inconsistent capitalization in branch names,    and inconsistent casing in pay_status values.

- Data type issues: Columns require type normalization: sale_date → date, and qty, unitPrice, total_amt, amt_paid → numeric.

## Cleaning Decisions

- Drop duplicated rows based on receipt_no,item_desc
- Handle missing values
- Normalize text (strip + lower + title)
- Convert data types

In [7]:
for col in df.select_dtypes(include="object"):
    df[col] = df[col].str.strip().str.lower().str.title()

df.head()

  receipt_no     sale_date  customer_name   contact_no      branch     item_desc    qty unitPrice total_amt pay_status    amt_paid                   source_note
0     R10000    2025/06/13   Sara Mohamed  01089254563    Downtown   Coffee 200G      2       110    220.00       Paid  Egp 220.00  Dashboard | First-Time Buyer
1     R10001   25-Jan-2025    Salma Nabil  01084093639  Heliopolis  Orange Juice  2 Pcs        38     76.00       Paid       76.00     Crm Export | New Customer
2     R10002    2025/01/19    Nadia Tamer  01153524491   Nasr City         Chips      5        22    110.00       Cash      110.00           Pos | Promo Applied
3     R10003    30-05-2025  Mostafa Samir  01030514014  Heliopolis      Rice 1Kg      2        48     96.00  Completed       48.00   Manual Excel | New Customer
4     R10004  Jun 10, 2025      Yara Atef  01275579548    Madinaty  Orange Juice      2       $38     76.00       Paid       76.00                     Pos | Vip

In [8]:
df.columns = df.columns.str.strip().str.lower()
df.head()

  receipt_no     sale_date  customer_name   contact_no      branch     item_desc    qty unitprice total_amt pay_status    amt_paid                   source_note
0     R10000    2025/06/13   Sara Mohamed  01089254563    Downtown   Coffee 200G      2       110    220.00       Paid  Egp 220.00  Dashboard | First-Time Buyer
1     R10001   25-Jan-2025    Salma Nabil  01084093639  Heliopolis  Orange Juice  2 Pcs        38     76.00       Paid       76.00     Crm Export | New Customer
2     R10002    2025/01/19    Nadia Tamer  01153524491   Nasr City         Chips      5        22    110.00       Cash      110.00           Pos | Promo Applied
3     R10003    30-05-2025  Mostafa Samir  01030514014  Heliopolis      Rice 1Kg      2        48     96.00  Completed       48.00   Manual Excel | New Customer
4     R10004  Jun 10, 2025      Yara Atef  01275579548    Madinaty  Orange Juice      2       $38     76.00       Paid       76.00                     Pos | Vip

In [9]:
df=df.drop_duplicates(subset=["receipt_no","item_desc"])
df.duplicated().sum()

np.int64(0)

In [10]:
# Convert dates
df["sale_date"] = pd.to_datetime(df["sale_date"],format="mixed",dayfirst=True, errors="coerce")
# Convert numeric
df["qty"]=df["qty"].replace(r"[^\d.]","",regex=True).pipe(pd.to_numeric)
df["unitprice"]=df["unitprice"].replace(r"[^\d.]","",regex=True).pipe(pd.to_numeric)
df["total_amt"]=df["total_amt"].replace(r"[^\d.]","",regex=True).pipe(pd.to_numeric)
df["amt_paid"]=df["amt_paid"].replace(r"[^\d.]","",regex=True).pipe(pd.to_numeric)

In [11]:
# Handle with Outliers + Consistency Rules

# recompute derived
df["total_amt"] = df["qty"] * df["unitprice"]

# remove invalid negatives
df = df[(df[['qty','unitprice','total_amt','amt_paid']] >= 0).all(axis=1)]

# enforce logical constraints
df = df[df["total_amt"] >= df["amt_paid"]]

# amount → status
df.loc[df['amt_paid'] == 0, 'pay_status'] = 'Pending'
df.loc[df['amt_paid'] == df['total_amt'], 'pay_status'] = 'Paid'
df.loc[(df['amt_paid'] > 0) & (df['amt_paid'] < df['total_amt']), 'pay_status'] = 'Partial'

# status → amount
df.loc[df["pay_status"].isin(["Paid","Cash"]), "amt_paid"] = df["total_amt"]
df.loc[df["pay_status"] == "Pending", "amt_paid"] = 0

# edge case
df.loc[df["qty"] == 0, "total_amt"] = 0

In [12]:
#Handle with NAN values
df[['sale_date','customer_name','contact_no']] = (
    df.groupby('receipt_no')[['sale_date','customer_name','contact_no']]
      .ffill()
      .bfill()
)
df=df.dropna(subset=["receipt_no"])

In [13]:
print(df.isna().sum()[lambda x: x!=0].sort_values(ascending=False))
print(df.info())
df.shape

Series([], dtype: int64)
<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, 0 to 329
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   receipt_no     258 non-null    object
 1   sale_date      258 non-null    datetime64[ns]
 2   customer_name  258 non-null    object
 3   contact_no     258 non-null    object
 4   branch         258 non-null    object
 5   item_desc      258 non-null    object
 6   qty            258 non-null    int64
 7   unitprice      258 non-null    float64
 8   total_amt      258 non-null    float64
 9   pay_status     258 non-null    object
 10  amt_paid       258 non-null    float64
 11  source_note    258 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 26.2+ KB
None

(258, 12)

In [14]:
# === DATA VALIDATION REPORT ===

# === CONFIG (EDIT PER PROJECT) ===
KEY = ['receipt_no','item_desc']
NON_NEGATIVE_COLS = ['qty','unitprice','total_amt','amt_paid']

DERIVED_RULES = {
    'total_amt': lambda df: df['total_amt'] == (df['qty'] * df['unitprice'])
}

print("=== DATA QUALITY SUMMARY ===")

# Shape
print(f"\nDataset size: {df.shape[0]} rows × {df.shape[1]} columns")

# Missing
missing = df.isna().sum()
missing = missing[missing != 0].sort_values(ascending=False)

print("\nMissing Values:")
if missing.empty:
    print("No missing values")
else:
    print(missing.to_string())

# 🔴 ASSERT — Missing
assert missing.empty, "Missing values still exist"

# KEY checks
print("\nKey Integrity:")

key_nan = df[KEY].isna().sum().sum()
print("Missing in key columns:",
      "No" if key_nan == 0 else f"Yes ({key_nan})")

# 🔴 ASSERT — Key missing
assert key_nan == 0, "Missing values in KEY columns"

key_dups = df.duplicated(subset=KEY).sum()
print("Duplicate records (based on key):",
      "No" if key_dups == 0 else f"Yes ({key_dups})")

# 🔴 ASSERT — Duplicates
assert key_dups == 0, "Duplicate records still exist"

# Value rules
print("\nValue Validation:")

if NON_NEGATIVE_COLS:
    neg_check = (df[NON_NEGATIVE_COLS] >= 0).all().all()
    print("No negative values in critical fields:",
          "Yes" if neg_check else "No")

    # 🔴 ASSERT — Negative values
    assert neg_check, "Negative values detected"

# 🔴 ASSERT — Overpayment
assert (df['amt_paid'] <= df['total_amt']).all(), "Overpayment detected"

# 🔴 ASSERT — Payment rule (المهم)
assert not (
    (df['pay_status'].isin(['Paid','Cash'])) &
    (df['amt_paid'] != df['total_amt'])
).any(), "Payment rule violated"

# Derived checks
print("\nCalculated Fields Consistency:")

for col, rule in DERIVED_RULES.items():
    valid = rule(df).all()
    print(f"{col} is consistent:",
          "Yes" if valid else "No")

    # 🔴 ASSERT — Derived fields
    assert valid, f"{col} calculation is inconsistent"

# Sample
print("\nSample Preview:")
display(df.head(3))

=== DATA QUALITY SUMMARY ===

Dataset size: 258 rows × 12 columns

Missing Values:
No missing values

Key Integrity:
Missing in key columns: No
Duplicate records (based on key): No

Value Validation:
No negative values in critical fields: Yes

Calculated Fields Consistency:
total_amt is consistent: Yes

Sample Preview:

  receipt_no  sale_date customer_name   contact_no      branch     item_desc  qty  unitprice  total_amt pay_status  amt_paid                   source_note
0     R10000 2025-06-13  Sara Mohamed  01089254563    Downtown   Coffee 200G    2      110.0      220.0       Paid     220.0  Dashboard | First-Time Buyer
1     R10001 2025-01-25   Salma Nabil  01084093639  Heliopolis  Orange Juice    2       38.0       76.0       Paid      76.0     Crm Export | New Customer
2     R10002 2025-01-19   Nadia Tamer  01153524491   Nasr City         Chips    5       22.0      110.0       Paid     110.0           Pos | Promo Applied

In [15]:
# === AFTER CLEANING (Quick Snapshot) ===

print(f"Shape: {df.shape[0]} rows × {df.shape[1]} cols")

print("\nMissing :")
display(df.isna().sum()[lambda x: x!=0].sort_values(ascending=False))

print("\nDuplicates (based on KEY):",
      df.duplicated(subset=KEY).sum())

print("\nSample:")
display(df.head(3))

Shape: 258 rows × 12 cols

Missing :

Series([], dtype: int64)

Duplicates (based on KEY): 0

Sample:

  receipt_no  sale_date customer_name   contact_no      branch     item_desc  qty  unitprice  total_amt pay_status  amt_paid                   source_note
0     R10000 2025-06-13  Sara Mohamed  01089254563    Downtown   Coffee 200G    2      110.0      220.0       Paid     220.0  Dashboard | First-Time Buyer
1     R10001 2025-01-25   Salma Nabil  01084093639  Heliopolis  Orange Juice    2       38.0       76.0       Paid      76.0     Crm Export | New Customer
2     R10002 2025-01-19   Nadia Tamer  01153524491   Nasr City         Chips    5       22.0      110.0       Paid     110.0           Pos | Promo Applied

In [16]:
df.to_csv("clean_data.csv", index=False)

In [17]:
check = pd.read_csv("clean_data.csv")
check.head()

  receipt_no   sale_date  customer_name   contact_no      branch     item_desc  qty  unitprice  total_amt pay_status  amt_paid                   source_note
0     R10000  2025-06-13   Sara Mohamed  01089254563    Downtown   Coffee 200G    2      110.0      220.0       Paid     220.0  Dashboard | First-Time Buyer
1     R10001  2025-01-25    Salma Nabil  01084093639  Heliopolis  Orange Juice    2       38.0       76.0       Paid      76.0     Crm Export | New Customer
2     R10002  2025-01-19    Nadia Tamer  01153524491   Nasr City         Chips    5       22.0      110.0       Paid     110.0           Pos | Promo Applied
3     R10003  2025-05-30  Mostafa Samir  01030514014  Heliopolis      Rice 1Kg    2       48.0       96.0    Partial      48.0   Manual Excel | New Customer
4     R10004  2025-06-10      Yara Atef  01275579548    Madinaty  Orange Juice    2       38.0       76.0       Paid      76.0                     Pos | Vip

## Summary

- Removed duplicates
- Handled missing values
- Normalized text columns
- Fixed data types
- Dataset is ready for analysis